name: Release Action-vnext

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the Docker image and load it locally.
      - name: Build Docker image (latest tag)
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          load: true
          tags: action-vnext:latest

      - name: Get Current Version
        id: current
        run: |
          CURRENT=$(git describe --tags --abbrev=0 --match "v*" 2>/dev/null || echo "v0.0.0")
          CURRENT=${CURRENT#v}
          echo "version=$CURRENT" >> $GITHUB_OUTPUT

      - name: Compute Next Version
        id: next
        run: |
          docker compose run -e LOG_LEVEL=debug --rm vnext
          VERSION=$(docker compose run --rm vnext)
          echo "Computed version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Gate
        id: gate
        run: |
          echo "Current version: ${{ steps.current.outputs.version }}"
          echo "Next version: ${{ steps.next.outputs.version }}"
          echo "Should release?: ${{ steps.current.outputs.version != steps.next.outputs.version }}"
          echo "continue=${{ steps.current.outputs.version != steps.next.outputs.version }}" >> $GITHUB_OUTPUT

      # Only if the computed version differs from the current version.
      - name: Create and Push Git Tag
        if: steps.gate.outputs.continue == 'true'
        run: |
          git tag "v${{ steps.next.outputs.version }}"
          git push --tags

      - name: Build and Push Docker Image with Version Tag
        if: steps.gate.outputs.continue == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:v${{ steps.next.outputs.version }}

      - name: Create GitHub Release
        if: steps.gate.outputs.continue == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.next.outputs.version }}
